spring:
#sql日志打印
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
#日志级别
logging:
  level:
    root: info
    org :
      hibernate: info
      springframework:
        web: info
#session 有效时间
server:
  servlet:
    session:
      timeout: 600s

