spring:
  application:
    name: qiyue-cloud-gateway
server:
  port: 7001
eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
zuul:
  routes:
    qiyue-cloud-crawler: /crawler/**
    qiyue-cloud-user: /user/**
    qiyue-cloud-weChat: /weChat/**
