spring:
  application:
    name: qiyue-cloud-gateway
server:
  port: 7001
eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
zuul:
  routes:
    qiyue-cloud-crawler: /crawler/**
    qiyue-cloud-user: /user/**
