server:
  port: 7000                    # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: qiyue-cloud-server        # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
